services:
  stats-server:
    build: ./ewm-stats-service
    image: ewm-stats-service
    container_name: ewm-stats-service
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm-stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ewm-stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    healthcheck:
      test: pg_isready -q -d ewm-stats -U stats
      interval: 5s
      timeout: 5s
      retries: 10
