create table if not exists endpoint_hits (
    id bigint generated by default as identity primary key,
    app varchar(128) not null,
    uri varchar(2048) not null,
    ip varchar(64) not null,
    hit_timestamp timestamp without time zone not null
);

create index if not exists idx_endpoint_hits_timestamp on endpoint_hits (hit_timestamp);
create index if not exists idx_endpoint_hits_uri on endpoint_hits (uri);
create index if not exists idx_endpoint_hits_ip on endpoint_hits (ip);
create index if not exists idx_endpoint_hits_uri_ip_timestamp on endpoint_hits (uri, ip, hit_timestamp);
