create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(250) not null,
    email varchar(254) not null,
    constraint uq_email unique (email)
);

create table if not exists categories (
    id bigint generated by default as identity primary key,
    name varchar(50) not null,
    constraint uq_category_name unique (name)
);

create table if not exists events (
    id bigint generated by default as identity primary key,
    annotation varchar(2000) not null,
    category_id bigint not null references categories (id),
    created_on timestamp without time zone not null,
    description varchar(7000) not null,
    event_date timestamp without time zone not null,
    initiator_id bigint not null references users (id),
    lat real not null,
    lon real not null,
    paid boolean not null,
    participant_limit integer not null default 0,
    published_on timestamp without time zone,
    request_moderation boolean not null default true,
    state varchar(20) not null,
    title varchar(120) not null,
    views bigint not null default 0
);

create table if not exists participation_requests (
    id bigint generated by default as identity primary key,
    created timestamp without time zone not null,
    event_id bigint not null references events (id),
    requester_id bigint not null references users (id),
    status varchar(20) not null,
    constraint uq_request unique (requester_id, event_id)
);

create table if not exists event_views (
    id bigint generated by default as identity primary key,
    event_id bigint not null references events (id) on delete cascade,
    ip varchar(64) not null,
    constraint uq_event_view unique (event_id, ip)
);

create table if not exists event_reactions (
    id bigint generated by default as identity primary key,
    event_id bigint not null references events (id) on delete cascade,
    user_id bigint not null references users (id) on delete cascade,
    reaction_type varchar(20) not null,
    created timestamp without time zone not null,
    updated timestamp without time zone not null,
    constraint uq_event_reaction unique (event_id, user_id),
    constraint chk_event_reaction_type check (reaction_type in ('LIKE', 'DISLIKE'))
);

create table if not exists compilations (
    id bigint generated by default as identity primary key,
    title varchar(50) not null,
    pinned boolean not null default false
);

create table if not exists compilation_events (
    compilation_id bigint not null references compilations (id) on delete cascade,
    event_id bigint not null references events (id) on delete cascade,
    primary key (compilation_id, event_id)
);

create index if not exists idx_events_category on events (category_id);
create index if not exists idx_events_initiator on events (initiator_id);
create index if not exists idx_events_state on events (state);
create index if not exists idx_events_event_date on events (event_date);
create index if not exists idx_event_views_event on event_views (event_id);
create index if not exists idx_event_reactions_event on event_reactions (event_id);
create index if not exists idx_event_reactions_user on event_reactions (user_id);
create index if not exists idx_event_reactions_event_type on event_reactions (event_id, reaction_type);
create index if not exists idx_requests_event_status on participation_requests (event_id, status);
create index if not exists idx_requests_requester on participation_requests (requester_id);
